# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RemoteRenderer
                                 A QGIS plugin
 Communicates with other programs via sockets and renders requested extents
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-08-19
        copyright            : (C) 2019 by BOKU ILEN
        email                : invalid@email.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RemoteRenderer class from file RemoteRenderer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .remote_renderer import RemoteRenderer
    return RemoteRenderer(iface)
