# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RemoteRenderer
                                 A QGIS plugin
 Communicates with other programs via sockets and renders requested extents
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2019-08-19
        git sha              : $Format:%H$
        copyright            : (C) 2019-20 by ILEN, BOKU Vienna
        email                : landscapelab@boku.ac.at
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
from qgis.core import QgsMessageLog
from .config import config

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .remote_renderer_dialog import RemoteRendererDialog
import os.path
from .RemoteRendering import RemoteRendering


class RemoteRenderer:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'RemoteRenderer_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Remote Renderer')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

        self.rendering_task = None
        self.re_render_action = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('RemoteRenderer', message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None
    ):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        start_icon_path = ':/plugins/remote_renderer/icon.png'
        refresh_icon_path = ':/plugins/remote_renderer/resources/icon_refresh.png'
        self.add_action(
            start_icon_path,
            text=self.tr(u'Toggle Remote Rendering'),
            callback=self.toggle_rendering,
            parent=self.iface.mainWindow()
        )

        self.re_render_action = self.add_action(
            refresh_icon_path,
            text=self.tr(u'Re-Render Last Request'),
            callback=self.re_render_last_request,
            parent=self.iface.mainWindow(),
            enabled_flag=False
        )

        # will be set False in run()
        self.first_start = True

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        if self.render_task_active():
            RemoteRendering.stop_remote_rendering_task()

        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Remote Renderer'),
                action)
            self.iface.removeToolBarIcon(action)

    # this is the default method generated when using the QGIS Plugin Builder, here it goes unused
    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = RemoteRendererDialog()

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass

    # turns remote rendering task on / off
    def toggle_rendering(self):

        if self.render_task_active():
            RemoteRendering.stop_remote_rendering_task()
        else:
            self.rendering_task = RemoteRendering.start_remote_rendering_task(self.update_re_render_action)

    # checks if remote rendering task is active
    def render_task_active(self):
        if self.rendering_task is None:
            return False

        return self.rendering_task.active

    # checks if there has been a previous render request and repeats the render process
    def re_render_last_request(self):
        if self.is_re_render_possible():
            self.rendering_task.handle_request(self.rendering_task.last_request)
            return

        QgsMessageLog.logMessage('could not re render last request', config.MESSAGE_CATEGORY, Qgis.Warning)

    # checks if the re render action can be performed and sets its enabled state accordingly
    def update_re_render_action(self):
        if self.is_re_render_possible():
            self.re_render_action.setEnabled(True)
        else:
            self.re_render_action.setEnabled(False)

    def is_re_render_possible(self):
        if self.rendering_task:
            if self.rendering_task.active:
                if self.rendering_task.last_request:
                    return True
        return False
